services:
  dbotkt:
    container_name: DBotKT
    restart: always
    image: paulinoo/dbotkt:latest
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YT_REFRESH_TOKEN=${YT_REFRESH_TOKEN}
      - PREFIXES=! . # Space-separated list of command prefixes
      - ADMIN_IDS=${ADMIN_IDS} # Comma-separated list of admin IDs
      - YTDLP_PATH=${YTDLP_PATH} # Path to yt-dlp binary
      - YT_CIPHER=http://ejs-api:8001 # URL of the ejs-api service
      - YT_CIPHER_PASSWORD=${YT_CIPHER_PASSWORD} # Password for accessing the ejs-api service
    networks:
      - internal_network

  ejs-api:
    image: ghcr.io/kikkia/yt-cipher:master
    container_name: ejs_signature_api
    environment:
      - API_TOKEN=${YT_CIPHER_PASSWORD} # Password for accessing the API
    restart: unless-stopped
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
