services:
  dbotkt:
    container_name: DBotKT
    restart: always
    image: paulinoo/dbotkt:latest
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YT_REFRESH_TOKEN=${YT_REFRESH_TOKEN}
      - PREFIXES=! . # Space-separated list of command prefixes
      - ADMIN_IDS=${ADMIN_IDS} # Comma-separated list of admin IDs
